# Generated by Django 4.2.29 on 2026-04-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
