# Generated by Django 4.2.29 on 2026-04-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
